### ISSUE TITLE
Pirate Weather (Darksky Replacement)

### ISSUE THREAD

**Issue by jazzyisj** [jazzyisj/home-assistant-config#15]
No replacement for:
- forecast/summary
- humidity forecast  - states('sensor.dark_sky_humidity_0d')
- wind gust forecast
- precipitation type forecast
- nearest storm distance/direction
- alert description, start/end

#DARKSKY

**Comment by jazzyisj** [comment]
Pirate weather - no alerts from Envcan

**Comment by jazzyisj** [comment]
- Minutely, Hourly, Daily summaries don't work
- No weather alerts
- Storm direction / distance don't work

**Comment by jazzyisj** [comment]
Storm distance/bearing not working - https://github.com/Pirate-Weather/pirateweather/issues/121

**Comment by alpha520098** [comment]
> Storm distance/bearing not working - [Pirate-Weather/pirateweather#121](https://github.com/Pirate-Weather/pirateweather/issues/121)

It was my understanding that alexander has this working in the beta form
